config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"
  resources :recipes do
    member do
      patch :update_public
    end
  end
  resources :inventories do 
    get 'shopping_list/:recipe_id', to: 'inventories#shopping_list', as: 'shopping_list'
  end
  resources :foods, only: [:create, :destroy]
  resources :inventory_foods, only: [:create, :destroy]
  resources :recipe_foods, only: [:create, :destroy, :update]
  
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :foods, through: :inventory_foods
  validates :name, presence: true

  validates :description, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def show
    @inventory = Inventory.includes(inventory_foods: :food).find_by_id(params[:id])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      redirect_to inventories_path, notice: 'Inventory created Successfully.'
    else
      render :new, alert: 'Could not create inventory.'
    end
  end

  def destroy
    @inventory = Inventory.find_by_id(params[:id])
    @inventory.destroy

    if @inventory.destroyed?
      flash[:notice] = 'Successfully deleted inventory.'
      redirect_to inventories_path
    else
      flash[:alert] = 'Could not delete inventory.'
      redirect_back(fallback_location: inventories_path)
    end
  end

  def shopping_list
    @inventory = Inventory.includes(inventory_foods: :food).find_by_id(params[:inventory_id])
    @recipe = Recipe.includes(recipe_foods: :food).find_by_id(params[:recipe_id])

    @missing_foods = []

    @recipe.recipe_foods.each do |recipe_food|
      inventory_food = @inventory.inventory_foods.find { |f| f.food_id == recipe_food.food_id }

      next unless inventory_food.nil? || inventory_food.quantity < recipe_food.quantity

      missing_quantity = inventory_food.nil? ? recipe_food.quantity : recipe_food.quantity - inventory_food.quantity
      cost = (missing_quantity / recipe_food.quantity) * recipe_food.food.price
      @missing_foods << { name: recipe_food.food.name, missing_quantity:, cost: }
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description).merge(user: current_user)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div id="inventory-list">
  <% if current_user %>
    <h1>Your Inventories</h1>
    <div class="d-flex justify-content-end">
      <%= link_to "add inventory", new_inventory_path, class: "btn btn-primary"%>
    </div>
    <% if @inventories.empty? %>
      <p>No inventories yet.</p>
    <% else %>
      <% @inventories.each do |inventory| %>
        <div class="inventory-card">
          <div class="inventory-card-header gap-5">
              <%= link_to inventory.name, inventory_path(inventory.id), class: "inventory-card-name" %>
              <p class="inventory-card-description text-start"><%= inventory.description %></p> 
          </div>
          <% if can? :destory, inventory%>
            <%= button_to "Remove", inventory_path(inventory.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "inventory-card-link inventory-card-link-remove text-danger" %>
          <%end%>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/inventories/new.html.erb
<%= form_with(model: @inventory, local: true) do |f|%>
  <%= f.text_field :name, placeholder: "inventory name", class: "form-control mb-2" %>
  <%= f.text_area :description, placeholder: "inventory description", class: "form-control mb-2" %>
  <%= f.submit "create", class: "btn btn-primary" %>
<%end%>

app/views/inventories/shopping_list.html.erb
<section>
  <h1>shopping list</h1>
  <div class="d-flex justify-content-between">
    <p>Amount of food to buy: <%= @missing_foods.length%></p>
    <p>Recipe: <%= link_to @recipe.name, recipe_path(@recipe.id)%></p>
  </div>
  <div class="d-flex justify-content-between">
    <% total_cost = @missing_foods.sum { |missing_food| missing_food[:cost] } %>
    <p>Total value of food needed: <%= total_cost %></p>
    <p>Inventory: <%= link_to @inventory.name, inventory_path(@inventory.id)%></p>
  </div>
  <table class="table border-top-2">
    <thead>
      <tr class="table-secondary">
        <th class="border-top-0 border border-2">Food</th>
        <th class="border-top-0 border border-2">Quantity</th>
        <th class="border-top-0 border border-2">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @missing_foods.each do |i| %>
        <tr>
          <td class="border-top-0 border border-2"><%= i[:name]%></td>
          <td class="border-top-0 border border-2"><%= i[:missing_quantity]%></td>
          <td class="border-top-0 border border-2"><%= i[:cost]%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</section>

app/views/inventories/show.html.erb
<section>
  <div class="d-flex flex-column mb-3 pb-2 border-2 border-dark border-bottom">
    <h1 class="text-center"><%= @inventory.name%></h1>
    <button class="ms-auto" id="food-btn" data-controller="modal" data-modal-id="food-form" data-action="click->modal#controlModal">add food</button>
  </div>
  <table class="table border-top-2">
    <thead>
      <tr class="table-secondary">
        <th class="border-top-0 border border-2">Food</th>
        <th class="border-top-0 border border-2">Quantity</th>
        <th class="border-top-0 border border-2">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @inventory.inventory_foods.each do |i| %>
        <tr>
          <td class="border-top-0 border border-2"><%= i.food.name%></td>
          <td class="border-top-0 border border-2"><%= i.quantity%><%= i.food.measurement_unit%></td>
          <td class="border-top-0 border border-2"><%= button_to "Remove", food_path(i.food.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: "btn fw-bold text-primary"%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <%= form_with(model: [ @inventory.inventory_foods.build ], local: true, class: "d-none position-absolute top-50 start-50 translate-middle bg-secondary w-50 p-4", id: "food-form") do |f| %>
    <%= f.hidden_field :inventory_id, value: @inventory.id %>
		<div class="mb-2">
			<%= f.number_field :quantity, min: 0, placeholder: 'quantity', class: 'form-control' %>
		</div>
    <%= f.fields_for :food, @inventory.foods.build do |food_fields| %>
			<div class="mb-2">
				 <%= food_fields.text_field :name, placeholder: 'name', class: 'form-control' %>
			</div>
			<div class="mb-2">
				<%= food_fields.number_field :price, min: 0, placeholder: 'price', class: 'form-control' %>
			</div>
			<div class="mb-2">
				 <%= f.label :measurement_unit, class: "text-light"%>
				<%= food_fields.select :measurement_unit, ["mg", "g", "kg"], class: 'form-control' %>
			</div>
    <% end %>
    <%= f.submit "add", class: "btn btn-primary" %>
  <% end %>
</section>