config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"
  resources :recipes do
    member do
      patch :update_public
    end
  end
  resources :inventories do 
    get 'shopping_list/:recipe_id', to: 'inventories#shopping_list', as: 'shopping_list'
  end
  resources :foods, only: [:create, :destroy]
  resources :inventory_foods, only: [:create, :destroy]
  resources :recipe_foods, only: [:create, :destroy, :update]
  
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    # recipe = Recipe.where(user_id: current_user.id)
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
  end

  # def create
  # end

  def destroy 
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.destroy
      flash[:notice] = "recipe deleted"
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  def public_recipe
    @recipes = Recipe.where(public: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:public_recipes]
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find_by_id(params[:id])
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe Created'
      redirect_to recipes_path
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.destroy
      flash[:notice] = 'recipe deleted'
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  def public_recipes
    @recipes = Recipe.select('recipes.*, COUNT(recipe_foods.id) AS food_count, SUM(foods.price) AS total_price')
      .left_outer_joins(:user, recipe_foods: :food)
      .where(public: true)
      .group('recipes.id, users.id')
      .order(created_at: :desc)
  end

  def update_public
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.toggle!(:public)
      flash[:notice] = 'public state updated'
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time,
                                   :public).merge(user_id: current_user.id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<section>
  <%= link_to "add new recipe", new_recipe_path, class: 'btn btn-success mb-3'%>
  <ul class="list-unstyled d-flex flex-column gap-3"> 
    <%@recipes.each do |recipe|%>
      <li class="d-flex gap-5 border border-2 p-2">
        <div class="w-25">
            <%= link_to recipe_path(recipe) do%>
              <h3 class="fs-3"><%= recipe.name%></h3>
            <%end%>
            <% if can? :destroy, recipe%>
              <%= button_to "Remove", recipe_path(recipe.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'%>
            <% end %>
        </div>
        <div class="w-75">
          <p><%= recipe.description%></p>
        </div>
      </li>
    <%end%>
  </ul>
</section>

app/views/recipes/new.html.erb
<%= form_with(model: @recipe, local:true) do |f|%>
  <%= f.text_field :name, placeholder: "recipe name", class: "form-control mb-2"%>
  <%= f.text_area :description, placeholder: "recipe description", class: "form-control mb-2"%>
  <%= f.number_field :cooking_time, placeholder: "cooking time: hours", class: "form-control mb-2"%>
  <%= f.number_field :preparation_time, placeholder: "preparation time: hours", class: "form-control mb-2"%>
  <div class="mb-2">
    <%= f.label :public%>
    <%= f.check_box :public%>
  <div>
  <%= f.submit "Create", class:"btn btn-primary mt-2"%>
<%end%>

app/views/recipes/public_recipes.html.erb
<section>
  <h1 class="text-center">Public Recipes</h1>
  <ul class="list-unstyled d-flex flex-column gap-3"> 
    <%@recipes.each do |recipe|%>
      <li class="d-flex gap-5 border border-2 p-2">
        <div class="w-25">
            <%= link_to recipe_path(recipe) do%>
              <h3 class="fs-3"><%= recipe.name%></h3>
            <%end%>
              <p class="fs-5 fw-bold">By: <%= recipe.user.name%></p>
        </div>
        <div class= "w-75">
          <p class="fs-5 fw-bold">Total Food Items: <%= recipe.food_count%></p>
          <p class="fs-5 fw-bold">Total Price: $<%= recipe.total_price || 0%></p>
        </div>
      </li>
    <%end%>
  </ul>
</section>

app/views/recipes/show.html.erb
<section>
  <h1 class="text-center"><%= @recipe.name%></h1>
  <div class="d-flex justify-content-between">
    <div><p><strong>preparation time:</strong> <%= @recipe.preparation_time%> hours</p></div>
    <% if can? :update, @recipe%>
      <div class= "d-inline-flex w-25 gap-3 align-items-center">
        <span class="fs-4">Public</span>
        <%= button_to update_public_recipe_path(@recipe), method: :patch, class: (@recipe.public ? 'bg-success' : 'bg-danger') + ' btn' do %>
          <%= @recipe.public ? 'on' : 'off' %>
        <% end %>

      </div>
    <% end %>
  </div>
  <div>
    <p><strong>Cooking time:</strong> <%= @recipe.cooking_time%> hours</p>
  </div>
  <div>
    <h3>instructions</h3>
    <p><%= @recipe.description%></p>
  </div>
  <div class="d-flex justify-content-between border-bottom border-2 pb-2">
    <button data-controller="modal" data-modal-id="shopping-list-generator" data-action="click->modal#controlModal">Generate shopping list</button>
    <%if can? :update, @recipe%>
      <button class="ms-auto" id="food-btn" data-controller="modal" data-modal-id="food-form" data-action="click->modal#controlModal">add ingredient</button>
    <%end%>
  </div>
  <table class="table border-top-2">
    <thead>
      <tr class="table-secondary">
        <th class="border-top-0 border border-2">Food</th>
        <th class="border-top-0 border border-2">Quantity</th>
        <th class="border-top-0 border border-2">Value</th>
        <th class="border-top-0 border border-2">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |rf|%>
        <tr>
          <td class="border-top-0 border border-2"><%= rf.food.name%></td>
          <td class="border-top-0 border border-2"><%= rf.quantity%><%= rf.food.measurement_unit%></td>
          <td class="border-top-0 border border-2">$<%= rf.food.price%></td>
          <td class="border-top-0 border border-2">
            <div class="d-flex gap-3">
              <button class="btn btn-success" data-controller="modal" data-modal-id="edit_recipe_food_<%= rf.id %>"data-action="click->modal#controlModal">Modify</button>
              <%= button_to "Remove", food_path(rf.food.id), method: :delete, data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, class: 'btn btn-danger'%>
            </div>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <%= form_with(model: [ @recipe.recipe_foods.build ], local: true, class: "d-none position-absolute top-50 start-50 translate-middle bg-secondary w-50 p-4", id: "food-form") do |f| %>
    <%= f.hidden_field :recipe_id, value: @recipe.id %>
		<div class="mb-2">
			<%= f.number_field :quantity, min: 0, placeholder: 'quantity', class: 'form-control' %>
		</div>
    <%= f.fields_for :food, @recipe.foods.build do |food_fields| %>
			<div class="mb-2">
				 <%= food_fields.text_field :name, placeholder: 'food name', class: 'form-control' %>
			</div>
			<div class="mb-2">
				<%= food_fields.number_field :price, min: 0, placeholder: 'price', class: 'form-control' %>
			</div>
			<div class="mb-2">
				 <%= f.label :measurement_unit, class: "text-light"%>
				<%= food_fields.select :measurement_unit, ["mg", "g", "kg"], class: 'form-control' %>
			</div>
    <% end %>
    <%= f.submit "add", class: "btn btn-primary" %>
  <% end %>
  
  <% @recipe.recipe_foods.each do |rf| %>
    <%= form_with(model: rf, local: true, class: "d-none position-absolute top-50 start-50 translate-middle bg-secondary w-50 p-4", id: "edit_recipe_food_#{rf.id}") do |f| %>
      <%= f.hidden_field :recipe_id, value: @recipe.id %>
      <div class="mb-2">
        <%= f.number_field :quantity, min: 0, placeholder: 'quantity', class: 'form-control' %>
      </div>
      <%= f.fields_for :food do |food_fields| %>
        <div class="mb-2">
          <%= food_fields.text_field :name, placeholder: 'food name', class: 'form-control' %>
        </div>
        <div class="mb-2">
          <%= food_fields.number_field :price, min: 0, placeholder: 'price', class: 'form-control' %>
        </div>
        <div class="mb-2">
          <%= f.label :measurement_unit, class: "text-light"%>
          <%= food_fields.select :measurement_unit, ["mg", "g", "kg"], class: 'form-control' %>
        </div>
      <% end %>
      <%= f.submit "Update", class: "btn btn-primary" %>
    <% end %>
  <% end %>

  <div id="shopping-list-generator" class="d-none position-absolute top-50 start-50 translate-middle bg-light border-dark w-50 p-4">
    <%if @inventories.empty?%>
      <h1>Please Create an inventory first</h1>
    <%else%>
      <h1>Generating Shopping List</h1>
      <p>Choose an inventory</p>
      <div class="d-flex align-items-center justify-content-between">
        <select id="inventory-select" data-controller="link-update" data-action="change->link-update#updateLink">
          <% @inventories.each do |i|%>
            <option value="<%= i.id %>"><%= i.name %></option>
          <%end%>
        </select>
        <%= link_to "Generate", inventory_shopping_list_path(recipe_id: @recipe.id, inventory_id: @inventories.first.id), id: "generate-link", class: "btn btn-success" %>
      </div>
    <%end%>
  </div>

</section>