config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root "recipes#index"
  resources :recipes do
    member do
      patch :update_public
    end
  end
  resources :inventories do 
    get 'shopping_list/:recipe_id', to: 'inventories#shopping_list', as: 'shopping_list'
  end
  resources :foods, only: [:create, :destroy]
  resources :inventory_foods, only: [:create, :destroy]
  resources :recipe_foods, only: [:create, :destroy, :update]
  
  get 'public_recipes', to: 'recipes#public_recipes'
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, user_id: user.id
    can :manage, Inventory, user_id: user.id
  end
end

app/models/application_record.rb
# ApplicationRecord class
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :inventory_foods, dependent: :destroy
  has_many :inventory, through: :inventory_foods
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :measurement_unit, presence: true, inclusion: { in: %w[g mg kg], message: '%<value>s is not a valid unit' }
  validates :name, presence: true, length: { maximum: 120 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy
  has_many :foods, through: :inventory_foods
  validates :name, presence: true

  validates :description, presence: true
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
  accepts_nested_attributes_for :food

  validates :quantity, numericality: { greater_than_or_equal_to: 1 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  validates :name, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :cooking_time, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  accepts_nested_attributes_for :food
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipe, dependent: :destroy
  has_many :inventory, dependent: :destroy

  validates :name, presence: true, length: { maximum: 120 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def create; end

  def destroy
    @food = Food.find_by_id(params[:id])
    if @food.destroy
      flash[:notice] = 'food removed'
    else
      flash[:error] = @food.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def index
    # recipe = Recipe.where(user_id: current_user.id)
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find_by_id(params[:id])
  end

  # def create
  # end

  def destroy 
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.destroy
      flash[:notice] = "recipe deleted"
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  def public_recipe
    @recipes = Recipe.where(public: true)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:public_recipes]
  def index
    @recipes = Recipe.includes(:user).where(user_id: current_user.id)
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find_by_id(params[:id])
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe Created'
      redirect_to recipes_path
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.destroy
      flash[:notice] = 'recipe deleted'
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  def public_recipes
    @recipes = Recipe.select('recipes.*, COUNT(recipe_foods.id) AS food_count, SUM(foods.price) AS total_price')
      .left_outer_joins(:user, recipe_foods: :food)
      .where(public: true)
      .group('recipes.id, users.id')
      .order(created_at: :desc)
  end

  def update_public
    @recipe = Recipe.find_by_id(params[:id])
    if @recipe.toggle!(:public)
      flash[:notice] = 'public state updated'
    else
      flash[:error] = @recipe.errors.full_messages.to_sentence
    end
    redirect_to request.referrer
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time,
                                   :public).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# This module contains helper methods for the application
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="border-2 border-bottom mb-3">
  <nav class="d-flex align-items-center w-100">
    <div class="w-25">
      <p class="fs-4 fw-bold text-success">Recipe App</p>
    </div>
    <ul class="d-flex list-unstyled justify-content-start gap-5 ">
      <% if user_signed_in? %>
        <li><%= link_to 'My Recipes', recipes_path, class: "text-decoration-none text-primary fw-bold"%></li>
        <li><%= link_to 'My Inventories', inventories_path, class: "text-decoration-none text-primary fw-bold"%></li>
        <li><%= link_to 'Public Recipes', public_recipes_path, class: "text-decoration-none text-primary fw-bold"%></li>
        <li><%= link_to 'Logout', destroy_user_session_path, class: "text-decoration-none text-primary fw-bold"%></li>
        <%else%>
          <li><%= link_to 'Login', new_user_session_path, class: "text-decoration-none text-primary fw-bold"%></li>
          <li><%= link_to 'Sign up', new_user_registration_path, class: "text-decoration-none text-primary fw-bold"%></li>
      <%end%>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>

  <body>
    <main class="container pt-3">
      <%= render '/layouts/header'%>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-primary" role="alert">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>